### ISSUE TITLE
Problem Connection

### ISSUE THREAD

**Issue by aitorsedano** [jjdejong/esphome-airleaf#1]
First, thank you for sharing the project. I really want to be able to apply it in my fancoils installation. Could you help me with the connections? I have put the TX and RX of the Wemos d1 Mini to a TTL to RS485 converter and this, on the other side to the A B and the - of the AB- fancoil plate, but it does not work, they do not communicate. What am I doing wrong? Thank you very much!!!

**Comment by jjdejong** [comment]
Depends on your controller type. Mine doesn't have the RS485 chip and I directly connect to the TTL-serial connector (RX, TX, GND, +5V), that, by the way, also supplies power to the Wemos PCB. I also had to set a jumper (on the top right) to "RTU" mode.
![PXL_20240908_213201879 RAW-01 COVER(1)](https://github.com/user-attachments/assets/02a31ef1-1cdc-422b-85cf-15fb955051d8)

**Comment by aitorsedano** [comment]
It works!!! Thank you very much!!! Congratulations on the project, it's amazing!!! Is there a sensor that warns when the 3-way valve closes?

**Comment by jjdejong** [comment]
Good that you like it. The valve status appears in "Relay Status" (a string containing various relay statuses separated by "|"). The valve open status is indicated by the presence of strings "EV1" and "EV2" (for two possible valves). You can create a new dedicated sensor if you specifically want the valve status (the bits 0 and 1 of the modbus register are dedicated to valves 1 and 2).

**Comment by jjdejong** [comment]
By the way, do you know where to purchase Airleaf parts online, such as controller boards or valves? I could only purchase the full fancoils with specific controller boards via eBay from France.

—JJJ

On 9 September 2024 at 17:52:25, aitorsedano ***@***.***) wrote:

It works!!! Thank you very much!!! Congratulations on the project, it's amazing!!! Is there a sensor that warns when the 3-way valve closes?

**Comment by aitorsedano** [comment]
I live in Spain and they are sold under a brand called Thermor. It is relatively easy for me to get these plates. How many plates do I need? I ask because I can ask for a quote and I will tell you...
